apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: basic-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'git@github.com:Johnstx/Devops-monitoring.git' 
    path: 'argocd/apps/Elasticsearch-app'
    targetRevision: HEAD
  destination:
    server: "https://127.0.0.1:45671"
    # name: kind-elk
    namespace: elastic-app
  syncPolicy:
    automated:
      prune: true # This will delete resources that are no longer in the repository.
      selfHeal: true # This will automatically fix differences between the desired state in Git and the live state in the cluster.
